### ISSUE TITLE
Quick skills do not appear for OSX

### ISSUE THREAD

**Issue by jackfang888** [kg/ViramateInstaller#15]
### What's wrong?

Quick skills/summons do not work even when enabled in the settings.  There is space for them below the characters, but no icons appear there.  Please see https://imgur.com/a/fY57O3P

I've tried un/reinstalling the extension.

### What error messages (if any) are in the Chrome developer console? (Ctrl+Shift+I)

VM355:96 vms> External channel established
util.ts:34 10:21:48 GMT-0700 (MST)> onPageReady
util.ts:34 10:21:48 GMT-0700 (MST)> Not showing vira because we're on the top page
mobage-jssdk-client.3.7.7.min.js:5 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://connect.mobage.jp') does not match the recipient window's origin ('http://game.granbluefantasy.jp').
ja.send @ mobage-jssdk-client.3.7.7.min.js:5
e.sendMenubarLog @ mobage-menubar.2.4.3.min.js:27
(anonymous) @ mobage-menubar.2.4.3.min.js:1
(anonymous) @ mobage-menubar.2.4.3.min.js:27
M._emitToDocument @ mobage-jssdk-client.3.7.7.min.js:7
M.initialized @ mobage-jssdk-client.3.7.7.min.js:7
M.init @ mobage-jssdk-client.3.7.7.min.js:7
(anonymous) @ mobage-jssdk.js:1
(anonymous) @ mobage-jssdk.js:1
M._emitToDocument @ mobage-jssdk-client.3.7.7.min.js:7
M.ready @ mobage-jssdk-client.3.7.7.min.js:7
(anonymous) @ mobage-jssdk-client.3.7.7.min.js:7
(anonymous) @ mobage-jssdk-client.3.7.7.min.js:5
d.onload @ mobage-jssdk-client.3.7.7.min.js:5
load (async)
ia.createIframe @ mobage-jssdk-client.3.7.7.min.js:5
ia.createInvisibleIframe @ mobage-jssdk-client.3.7.7.min.js:5
ja.openTrackingCookieIframe @ mobage-jssdk-client.3.7.7.min.js:5
(anonymous) @ mobage-jssdk-client.3.7.7.min.js:7
(anonymous) @ mobage-jssdk-client.3.7.7.min.js:6
d.onload @ mobage-jssdk-client.3.7.7.min.js:5
load (async)
ia.createIframe @ mobage-jssdk-client.3.7.7.min.js:5
ia.createInvisibleIframe @ mobage-jssdk-client.3.7.7.min.js:5
(anonymous) @ mobage-jssdk-client.3.7.7.min.js:6
na.init @ mobage-jssdk-client.3.7.7.min.js:6
(anonymous) @ mobage-jssdk-client.3.7.7.min.js:7
(anonymous) @ mobage-jssdk-client.3.7.7.min.js:7
44util.ts:34 10:21:52 GMT-0700 (MST)> TypeError: Cannot read property 'map' of undefined
    at pushGameStatusInner (<anonymous>:1065:59)
    at pushGameStatus (<anonymous>:1111:17)
54util.ts:34 10:21:53 GMT-0700 (MST)> TypeError: Cannot read property 'map' of undefined
    at pushGameStatusInner (<anonymous>:1065:59)
    at pushGameStatus (<anonymous>:1111:17)
54util.ts:34 10:21:54 GMT-0700 (MST)> TypeError: Cannot read property 'map' of undefined
    at pushGameStatusInner (<anonymous>:1065:59)
    at pushGameStatus (<anonymous>:1111:17)
60util.ts:34 10:21:55 GMT-0700 (MST)> TypeError: Cannot read property 'map' of undefined
    at pushGameStatusInner (<anonymous>:1065:59)
    at pushGameStatus (<anonymous>:1111:17)
57util.ts:34 10:21:56 GMT-0700 (MST)> TypeError: Cannot read property 'map' of undefined
    at pushGameStatusInner (<anonymous>:1065:59)
    at pushGameStatus (<anonymous>:1111:17)
58util.ts:34 10:21:57 GMT-0700 (MST)> TypeError: Cannot read property 'map' of undefined
    at pushGameStatusInner (<anonymous>:1065:59)
    at pushGameStatus (<anonymous>:1111:17)

Cannot read property 'map' errors continue...

### What version of Viramate and Viramate Installer are you using? (Appears in the Viramate Options page)

Viramate: 2018.11.2.4
Installer: N/A (on OSX; installed from Chrome extension webstore)

### What version of Chrome are you using? (The first three lines of chrome://version/)

Vivaldi | 1.15.1147.64 (Stable channel) (64-bit)
Revision | 40a77e3ed05776b882a9944eb85f77c13ba3f3d9-
OS | Mac OS X

### What's your favorite color?

Blue!  I mean... WAAAAAAAAAGH!

**Comment by kg** [comment]
Partially fixed in latest version

**Comment by jackfang888** [comment]
Is the latest version what's on the extension store?

**Comment by jackfang888** [comment]
Looks like you fixed it in 2018.11.8.1, but a new problem has arisen: CPU usage goes to 100% when in a battle.

**Comment by jackfang888** [comment]
Looks like there's an infinite loop.  Getting the following in the console when skills are enabled:

`div.ico-ability43_3.ability-character-num-1-1 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability13_4.ability-character-num-1-2 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability2_3.ability-character-num-1-3 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability13_4.ability-character-num-1-4 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability141_1.ability-character-num-2-1 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability142_3.ability-character-num-2-2 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability143_2.ability-character-num-2-3 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability17_1.ability-character-num-3-1 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability341_3.ability-character-num-3-2 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability3_2.ability-character-num-3-3 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability295_3.ability-character-num-4-1 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability446_5.ability-character-num-4-2 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability43_3.ability-character-num-1-1 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability13_4.ability-character-num-1-2 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability2_3.ability-character-num-1-3 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability13_4.ability-character-num-1-4 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability141_1.ability-character-num-2-1 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability142_3.ability-character-num-2-2 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability143_2.ability-character-num-2-3 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability17_1.ability-character-num-3-1 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability341_3.ability-character-num-3-2 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability3_2.ability-character-num-3-3 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability295_3.ability-character-num-4-1 []
util.ts:34 13:52:25 GMT-0700 (MST)> rbl div.ico-ability446_5.ability-character-num-4-2 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability43_3.ability-character-num-1-1 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability13_4.ability-character-num-1-2 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability2_3.ability-character-num-1-3 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability13_4.ability-character-num-1-4 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability141_1.ability-character-num-2-1 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability142_3.ability-character-num-2-2 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability143_2.ability-character-num-2-3 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability17_1.ability-character-num-3-1 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability341_3.ability-character-num-3-2 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability3_2.ability-character-num-3-3 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability295_3.ability-character-num-4-1 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability446_5.ability-character-num-4-2 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability43_3.ability-character-num-1-1 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability13_4.ability-character-num-1-2 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability2_3.ability-character-num-1-3 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability13_4.ability-character-num-1-4 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability141_1.ability-character-num-2-1 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability142_3.ability-character-num-2-2 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability143_2.ability-character-num-2-3 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability17_1.ability-character-num-3-1 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability341_3.ability-character-num-3-2 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability3_2.ability-character-num-3-3 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability295_3.ability-character-num-4-1 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability446_5.ability-character-num-4-2 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability43_3.ability-character-num-1-1 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability13_4.ability-character-num-1-2 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability2_3.ability-character-num-1-3 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability13_4.ability-character-num-1-4 []
util.ts:34 13:52:26 GMT-0700 (MST)> rbl div.ico-ability141_1.ability-character-num-2-1 []`

etc.
