### ISSUE TITLE
v2018.11.23.1 doesn't work

### ISSUE THREAD

**Issue by wkykaos** [kg/ViramateInstaller#16]
### What's wrong?

Some features of the latest viramate update doesn't work and it keep telling me to reload the game and said no game tab found.

### What version of Viramate and Viramate Installer are you using? (Appears in the Viramate Options page)

Viramate v2018.11.23.1

Installer v2018.11.13.2

### What version of Chrome are you using? (The first three lines of chrome://version/)

Google Chrome: 71.0.3578.62 (Official Build) beta (64 bit) (cohort: Beta)

Revision: b1fa6dee27746dd62414ffad95ea3a7acf51ef16-refs/branch-heads/3578@{#760}

OS: Windows

### What's your favorite color?

Black

![2018y11m24d_002353890](https://user-images.githubusercontent.com/36138207/48953058-7a819d80-ef7f-11e8-8ceb-fb081566026b.png)
![2018y11m24d_002526832](https://user-images.githubusercontent.com/36138207/48953062-7eadbb00-ef7f-11e8-919b-f6f2c8325293.png)

**Comment by kg** [comment]
Can you show me the contents of the developer console in the granblue tab?

**Comment by wkykaos** [comment]
> Can you show me the contents of the developer console in the granblue tab?

![2018y11m24d_011408172](https://user-images.githubusercontent.com/36138207/48954928-75741c80-ef86-11e8-9b29-68abbe772b35.png)

**Comment by kg** [comment]
Thank you for the bug report. This is a bug in Google Chrome that I have reported on their bug tracker. In the interim, after 2 hours I found a workaround for the bug and have put the workaround in version 2018.11.23.2 of the extension.
