### ISSUE TITLE
[Bug report] Automatically ends raid failed

### ISSUE THREAD

**Issue by polarbear127** [kg/ViramateInstaller#3]
Hi,

I would like to report a bug.

The version of  viramate and installer are v2018.3.8.3 and v1.0.3.1 respectively. I noticed that the automatically ends raid function doesn't work.

Thanks,

**Comment by kg** [comment]
Are there any errors in the developer console?

**Comment by polarbear127** [comment]
Hi kg,

I didn't get any error or warning messages from developer console. 

Thanks,

**Comment by po456asd** [comment]
did you use chrome v65 ? try change into newer version or older version or change into chromuim and try again.

**Comment by polarbear127** [comment]
@po456asd thanks for your suggestion. However, even I tried to use Chromuim Version 65.0.3325.181 (Developer Build) (64-bit), the automatically end raids functions don't work either.  

May I know what version of Chrome/Chromuim you are using? Because there are memory over-used issue while playing GBF on Chrome version 64, I avoid using the earlier version.

Thanks,

**Comment by po456asd** [comment]
try use other than v 65
i use this one . maybe newer than this one should work too. 
![image](https://user-images.githubusercontent.com/13596788/37946874-12dfb634-31b2-11e8-857f-fca183c66e96.png)

**Comment by kg** [comment]
I managed to reproduce this and it is not a Viramate bug. It is either a bug in Chrome or in Granblue (my money's on Chrome). The problem is that Granblue never connects to the raid server so Viramate never sees a 'raid ended' event. If you pay close attention you will notice that in raids without working auto-end the boss's HP and debuffs update far slower than usual.

**Comment by po456asd** [comment]
yea chrome v 65 is somewhat bugged with many extension. maybe downgrade or use chromium instead to play granblue.

**Comment by polarbear127** [comment]
@kg you’re right! I noticed the problem yesterday. Do you think it would be better to check the rest HP of boss instead of connecting to raid server? 

@po456asd thank you for sharing your experience but the function doesn’t work well with v67 either. I think I should try to downgrade to v63 (v64 has memory over-used issue)....
