### ISSUE TITLE
Installation of Viramate installer fails "Could not create SSL/TLS secure channel"

### ISSUE THREAD

**Issue by jackfang888** [kg/ViramateInstaller#5]
### What's wrong?
Fails to install with the error below.  Also the `--disk` option doesn't work after I manually downloaded the manager.zip and ext.zip files and moved them into `AppData\Local\Viramate\Installer`

### What error messages (if any) are in the Chrome developer console? (Ctrl+Shift+I)
Viramate Installer v2018.3.20.2
Use viramate -? for info on command line switches
Installing extension. This'll take a moment...
Downloading https://viramate.luminance.org/manager.zip... The request was aborted: Could not create SSL/TLS secure channel.
Downloading https://viramate.luminance.org/ext.zip... The request was aborted: Could not create SSL/TLS secure channel.
Checking for installer update ... The request was aborted: Could not create SSL/TLS secure channel.
Failed to install extension.

### What version of Viramate and Viramate Installer are you using? (Appears in the Viramate Options page)
Viramate Installer v2018.3.20.2

### What version of Chrome are you using? (The first three lines of chrome://version/)
65.0.3325.162

### What's your favorite color?
Blue!  No, I mean-
Waaaaaaaaaaaaaaaaaaaaaaaah~!

**Comment by kg** [comment]
Does https://viramate.luminance.org load for you in iexplore.exe (Internet explorer, not Edge)?

**Comment by kg** [comment]
Try now. You might need to download the latest installer first (.3.22.1)

**Comment by jackfang888** [comment]
@kg Thanks!  That did the trick.
