### ISSUE TITLE
[bug report] Issue with queueing renewed skills

### ISSUE THREAD

**Issue by kokoropaint** [kg/ViramateInstaller#6]
### What's wrong?
When trying to queue Lady Katapillar and Vira's Full Barrage after using Refuel to use it twice in one turn, it will not let me add it to the queue (using quick skill or when going into the character's skill menu) until everything else has cleared. I'm unsure if this happens with any other skills, but I have been able to do this otherwise when playing on both mobile browser and a PC browser that does not have Viramate installed.

### What version of Viramate and Viramate Installer are you using? (Appears in the Viramate Options page)

I'm using version 2018.3.22.1 for Viramate and vers 2018.3.8.1 for the extension manager.

### What version of Chrome are you using? (The first three lines of chrome://version/)

Using Chrome version 65.0.3325.181 (Official Build) (64-bit) (cohort: Stable).

Thanks for the great extension, and I hope that this can be fixed.

**Comment by po456asd** [comment]
maybe try change chrome to other version from v65 because v65 is bugged with almost every extension somehow.

**Comment by wkykaos** [comment]
This is caused by the **stuck skill button workaround**, it prevent you to queue the same skill with cooldown that will give you network error and broke the quick skill button.

It has a compatibility fix for Romeo and Katapillar before and it seems not working now, you should uncheck that workaround when you use character with cooldown renew.

**Comment by kokoropaint** [comment]
Thanks so much! This fixed it. I'm fine with keeping it off until the workaround is fixed.

**Comment by kg** [comment]
Odd, I can't reproduce this. Can you record a video of it

**Comment by wkykaos** [comment]
You can't queue those renewed skill when workaround turn on like this.

[https://drive.google.com/file/d/1zM59iLAfq4oVu3LcAmxw-uYMN15CZci5/view?usp=sharing](url)

**Comment by kg** [comment]
Oh, I see! Thank you, I didn't understand the problem.
